name: Deploy Micro-Frontend

on:
  push:
    branches: [ portfolio-2, micro-apps ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build and Deploy
      run: |
        # Configure git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Switch to gh-pages
        git checkout gh-pages
        
        # Build Portfolio
        git checkout portfolio-2
        cd portfolio
        npm install
        npm run build -- --base-href=/frontcraft/
        cd ..
        
        # Build Dashboard
        git checkout micro-apps
        cd dashboard
        npm install
        npm run build -- --configuration=production --base-href=/frontcraft/dashboard/ --deploy-url=/frontcraft/dashboard/
        
        # Build Supply Chain
        ng build supply-chain --base-href=/frontcraft/supply-chain/ --deploy-url=/frontcraft/supply-chain/
        cd ..
        
        # Deploy to gh-pages
        git checkout gh-pages
        
        # Copy portfolio files
        cp -r portfolio/dist/portfolio/browser/* .
        
        # Copy dashboard files
        cp -r dashboard/dist/dashboard/* dashboard/
        
        # Copy supply-chain files
        cp -r dashboard/dist/supply-chain/* supply-chain/
        
        # Fix localhost URLs
        sed -i 's|http://localhost:4201/remoteEntry.js|https://nandhakumar1717.github.io/frontcraft/supply-chain/remoteEntry.js|g' dashboard/*.js
        
        # Commit and push
        git add .
        git commit -m "Auto-deploy: $(date)"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}