name: Deploy Portfolio + Micro-Frontend Apps

on:
  push:
    branches: [ micro-apps ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout micro-apps branch
        uses: actions/checkout@v4
        with:
          ref: micro-apps
          path: micro-apps
        
      - name: Checkout portfolio branch
        uses: actions/checkout@v4
        with:
          ref: portfolio-2
          path: portfolio
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Build Dashboard App
        run: |
          cd micro-apps/dashboard
          npm install --legacy-peer-deps --force
          npm run build -- --configuration=production --base-href=/frontcraft/dashboard/
          
      - name: Prepare deployment directory
        run: |
          mkdir -p deploy
          # Copy portfolio files from portfolio-2 branch (all files including hidden ones)
          cp -r portfolio/. deploy/
          # Copy dashboard app to subfolder
          mkdir -p deploy/dashboard
          cp -r micro-apps/dashboard/dist/dashboard/* deploy/dashboard/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true