name: Deploy Portfolio + Dashboard

on:
  push:
    branches: [ micro-apps ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout portfolio-2 branch
        uses: actions/checkout@v4
        with:
          ref: portfolio-2
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Checkout micro-apps for dashboard
        uses: actions/checkout@v4
        with:
          ref: micro-apps
          path: micro-apps
          
      - name: Build Dashboard
        run: |
          cd micro-apps/dashboard
          npm install --legacy-peer-deps --force
          npm run build -- --configuration=production --base-href=/frontcraft/dashboard/
          
      - name: Prepare deployment
        run: |
          mkdir -p deploy
          # Copy portfolio files to root
          cp -r * deploy/ || true
          rm -rf deploy/micro-apps deploy/.git
          # Copy dashboard to subfolder
          mkdir -p deploy/dashboard
          cp -r micro-apps/dashboard/dist/dashboard/* deploy/dashboard/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4